# Generated by Django 5.2.7 on 2026-04-13 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adaptive_engine", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptmastery",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="conceptnode",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concept_node",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="conceptmastery",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adaptive_engine.conceptnode",
            ),
        ),
        migrations.AddField(
            model_name="conceptdependency",
            name="prerequisite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unlocks",
                to="adaptive_engine.conceptnode",
            ),
        ),
        migrations.AddField(
            model_name="conceptdependency",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requires",
                to="adaptive_engine.conceptnode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conceptmastery",
            unique_together={("student", "node")},
        ),
        migrations.AlterUniqueTogether(
            name="conceptdependency",
            unique_together={("prerequisite", "target")},
        ),
    ]
